### ISSUE TITLE
找不到BR

### ISSUE THREAD

**Issue by luyuan2002** [zion223/NeteaseCloudMusic-MVVM#11]
![image](https://user-images.githubusercontent.com/34305780/105114714-65264080-5b02-11eb-93a4-1db24d768c5a.png)

**Comment by zion223** [comment]
编码问题  把 C:\Users\User\AndroidStudio4.0\config 路径下的studio64.exe.vmoptions文件加上-Dfile.encoding=UTF-8 然后重启AS就好了

**Comment by luyuan2002** [comment]
可以了
