### ISSUE TITLE
抓的接口失效了？

### ISSUE THREAD

**Issue by zs1973** [zion223/NeteaseCloudMusic-MVVM#14]
里面啥都没有8

**Comment by zion223** [comment]
服务器到期了

**Comment by zs1973** [comment]
> 服务器到期了
开源下server端的代码呗 本地跑跑看看

**Comment by zion223** [comment]
> > 服务器到期了
> > 开源下server端的代码呗 本地跑跑看看

https://github.com/Binaryify/NeteaseCloudMusicApi
