### ISSUE TITLE
账号密码咋没有

### ISSUE THREAD

**Issue by jakeliusir** [zion223/NeteaseCloudMusic-MVVM#16]

**Comment by zion223** [comment]
账号是你自己的网易云账号，密码是你自己的网易云音乐密码

**Comment by jakeliusir** [comment]
可是我填了说我账号密码不对，我用自己的网易云的手机号密码登陆就行，这是为什么呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zion223/NeteaseCloudMusic-MVVM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 上午10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zion223/NeteaseCloudMusic-MVVM] 账号密码咋没有 (Issue #16)





 
账号是你自己的网易云账号，密码是你自己的网易云音乐密码
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zion223** [comment]
PhoneLoginActivity.java  你可以看看这个类 登录时候是怎么返回的
