### ISSUE TITLE
程序闪退怎么办

### ISSUE THREAD

**Issue by jakeliusir** [zion223/NeteaseCloudMusic-MVVM#17]

**Comment by zion223** [comment]
贴个异常的Log吧  有时间处理下

**Comment by jakeliusir** [comment]
ok，先前那个基础版的网易云音乐，登陆不上去，是的我自己搭建后端么


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zion223/NeteaseCloudMusic-MVVM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zion223/NeteaseCloudMusic-MVVM] 程序闪退怎么办 (Issue #17)





 
贴个异常的Log吧  有时间处理下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zion223** [comment]
是的 多看看 README吧

**Comment by jakeliusir** [comment]
好的，感谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zion223/NeteaseCloudMusic-MVVM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zion223/NeteaseCloudMusic-MVVM] 程序闪退怎么办 (Issue #17)





 
是的 多看看 README吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
