### ISSUE TITLE
服务器关闭了吗？

### ISSUE THREAD

**Issue by Androidkobe** [zion223/NeteaseCloudMusic-MVVM#21]
打开一直在开屏页，提示建立链接失败

**Comment by dyjcow** [comment]
博主的服务器有问题了，可以使用这个看看
[广工数智Android考核api链接](https://api.lxtlovely.top/)

**Comment by zion223** [comment]
> 博主的服务器有问题了，可以使用这个看看 [广工数智Android考核api链接](https://api.lxtlovely.top/)

服务器本来就是要自己本地搭建的，服务器不是我维护的
