### ISSUE TITLE
大佬您好，想学习一下这个项目，但是发现BASE_URL是本地的，接口访问不了怎么办呀？

### ISSUE THREAD

**Issue by sjl164** [zion223/NeteaseCloudMusic-MVVM#23]
可以给一份服务端代码吗？
付费学习也可以的，谢谢了！

**Comment by sjl164** [comment]
String BASE_URL = "http://192.168.1.184:3000/";

**Comment by sjl164** [comment]
![image](https://github.com/zion223/NeteaseCloudMusic-MVVM/assets/16248600/dfa99dda-59d7-4a02-a2ec-b7b087e03949)

**Comment by zion223** [comment]
自己本地起一个服务换成自己的本机地址就行

**Comment by zpszz** [comment]
现在手机号根本登不进去
