### ISSUE TITLE
新下载下来,编译报错

### ISSUE THREAD

**Issue by jasonvzhao** [zion223/NeteaseCloudMusic-MVVM#3]
D:\code\NeteaseCloudMusic-MVVM-master\NeteaseCloudMusic-MVVM-master\app\src\main\java\com\netease\music\ui\page\cloud\CloudVillageFragment.java:11: ����: �Ҳ�������
import com.netease.music.BR;

Caused by: org.apache.xerces.impl.io.MalformedByteSequenceException: Invalid byte 3 of 3-byte UTF-8 sequence.

**Comment by zion223** [comment]
编码改成UTF-8格式

**Comment by jasonvzhao** [comment]
是USF-8的，具体哪个文件没显示------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;zion223&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月18日(星期天) 下午4:12
收件人:&nbsp;&quot;zion223/NeteaseCloudMusic-MVVM&quot;<NeteaseCloudMusic-MVVM@noreply.github.com&gt;;
抄送:&nbsp;&quot;jasonvzhao&quot;<1005879868@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zion223/NeteaseCloudMusic-MVVM] 新下载下来,编译报错 (#3)

**Comment by zion223** [comment]
在vm options里面改
