### ISSUE TITLE
服务器问题

### ISSUE THREAD

**Issue by tigerFF** [zion223/NeteaseCloudMusic-MVVM#7]
hub主，你那个服务器是不是到期了？

**Comment by zion223** [comment]
是的 没钱续费了 你可以自己本地搭一个

**Comment by tigerFF** [comment]
> 是的 没钱续费了 你可以自己本地搭一个

我自己搭的服务器进入APP主界面后会报错，hub主你有没有改服务器代码呀？

**Comment by zion223** [comment]
我没有改代码 看看报错原因 应该是我的服务器代码比较旧了

**Comment by tigerFF** [comment]
> 我没有改代码 看看报错原因 应该是我的服务器代码比较旧了

我知道了，用2.0版的那个代码就可以了，谢谢hub主热情解答

**Comment by tigerFF** [comment]
> 我没有改代码 看看报错原因 应该是我的服务器代码比较旧了

再打扰一下哈，hub主能说一下具体是2.几版的服务器嘛，主页可以了，歌单以及日推点进去也会闪退，报错空对象错误

**Comment by zion223** [comment]
具体我也忘记了，我没有及时更新它后端服务器的代码(，最近比较忙
