### ISSUE TITLE
少类？

### ISSUE THREAD

**Issue by AreYReady** [zion223/NeteaseCloudMusic-MVVM#8]
/Users/huangshunchao/StudioProjects/NeteaseCloudMusic-MVVM/app/src/main/java/com/netease/music/ui/page/adapter/notification/ForwardsMeAdapter.java:17: 错误: 找不到符号
import com.netease.lib_api.model.notification.ForwardsEventBean;
                                             ^
  符号:   类 ForwardsEventBean
  位置: 程序包 com.netease.lib_api.model.notification

少了ForwardsEventBean类
少了com.netease.lib_api.model.search.TopAlbumBean类

**Comment by zion223** [comment]
确实漏提交文件了

**Comment by zion223** [comment]
重新pull下代码
