### ISSUE TITLE
老哥跑不起来说没有br类

### ISSUE THREAD

**Issue by wangbincyzj** [zion223/NeteaseCloudMusic-MVVM#9]

**Comment by zion223** [comment]
附上报错信息看看

**Comment by wangbincyzj** [comment]
![image](https://user-images.githubusercontent.com/52363975/103196036-6955a880-491e-11eb-8a94-87d347d75671.png)

我刚刚学不太会

**Comment by zion223** [comment]
只有这一处BR找不到吗，我觉得是本地编译的问题

**Comment by wangbincyzj** [comment]
所有的BR都没有

**Comment by zion223** [comment]
先把 C:\Users\User\.AndroidStudio4.0\config 路径下的studio64.exe.vmoptions文件加上-Dfile.encoding=UTF-8
要不然控制台打印的中文都是乱码 再看看提示的中文是什么

**Comment by wangbincyzj** [comment]
![image](https://user-images.githubusercontent.com/52363975/103197409-eda92b00-4920-11eb-98ac-2cce0dd6ac38.png)
好了!就是编码问题

**Comment by zion223** [comment]
重新pull下代码 刚刚改了下

**Comment by wangbincyzj** [comment]
登录不了 什么原因啊

**Comment by zion223** [comment]
服务器到期了，  在https://github.com/zion223/NeteaseCloudMusic 的README有说明
